name: Beta
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build-beta:
    name: Build Beta
    uses: ./.github/workflows/common.yml
    with:
      type: Beta
    secrets: inherit
